version: '3.8'

services:
    nats-server:
        image: nats:latest
        ports:
            - 8222:8222

    gateway:
        depends_on:
            - nats-server
        container_name: gateway
        restart: unless-stopped
        build:
            target: dev
            context: ./gateway
            dockerfile: Dockerfile
        volumes:
            - ./gateway/src:/usr/src/app/src
        environment:
            PORT: ${GATEWAY_PORT}
            NATS_SERVERS: ${NATS_SERVERS}
        ports:
            - "${PORT:-3000}:${PORT:-3000}"
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: "512m"
                reservations:
                    cpus: "0.25"
                    memory: "256m"

    authentication-database:
        container_name: authentication-database
        image: postgres:16.2
        restart: always
        volumes:
            - ./authentication/postgres:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: ${POSTGRES_USER_AUTH}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_AUTH}
            POSTGRES_DB: ${POSTGRES_DB_AUTH}

    authentication:
        depends_on:
            - nats-server
            - authentication-database
        container_name: authentication
        restart: unless-stopped
        environment:
            PORT: ${AUTHENTICATION_PORT}
            NATS_SERVERS: ${NATS_SERVERS}
            JWT_SECRET: ${JWT_SECRET}
            POSTGRES_USER: ${POSTGRES_USER_AUTH}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_AUTH}
            POSTGRES_DB: ${POSTGRES_DB_AUTH}
            PORT_DB: ${PORT_DB_AUTH}
            HOST_DB: ${HOST_DB_AUTH}
        build:
            target: dev
            context: ./authentication
            dockerfile: Dockerfile
        ports:
            - "${PORT:-3001}:${PORT:-3001}"
        volumes:
            - ./authentication/src:/app/src
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: "512m"
                reservations:
                    cpus: "0.25"
                    memory: "256m"